define([
	"pointing_game/modules/pointing_module_1-12",
	"pointing_game/modules/pointing_module_1-20",
	"pointing_game/modules/pointing_module_days",
	"pointing_game/modules/pointing_module_months",
	"pointing_game/modules/pointing_module_dates",
	"pointing_game/modules/pointing_module_subjects",
	"pointing_game/modules/pointing_module_fruits",
	"pointing_game/modules/pointing_module_study_time",
	"pointing_game/modules/pointing_module_action_verbs",
	"pointing_game/modules/pointing_module_colors",
	"pointing_game/modules/pointing_module_summer_vacation_plan",
	"pointing_game/modules/pointing_module_family",
	"pointing_game/modules/pointing_module_A-Z",
	"pointing_game/modules/pointing_module_A-Z_lowercase",
	"pointing_game/modules/pointing_module_weather",
	"pointing_game/modules/pointing_module_prepositions",
	"pointing_game/modules/pointing_module_stationery",
	"pointing_game/modules/pointing_module_bedroom",
	"pointing_game/modules/pointing_module_jobs",
	"pointing_game/modules/pointing_module_countries",
	"pointing_game/modules/pointing_module_buildings",
	"pointing_game/modules/pointing_module_categories",
	"pointing_game/modules/pointing_module_zodiac",
	"pointing_game/modules/pointing_module_vegetables",
	"pointing_game/modules/pointing_module_colored_shapes",
	"pointing_game/modules/pointing_module_school_events",
	"pointing_game/modules/pointing_module_foods",
	"pointing_game/modules/pointing_module_body_parts",
	"pointing_game/modules/pointing_module_prices"
], function (
	m12,
	m20,
	mDays,
	mMonths,
	mDates,
	mSubjects,
	mFruits,
	mStudyTime,
	mActionVerbs,
	mColors,
	mSummerVacationPlan,
	mFamily,
	mAZ,
	maz,
	mWeather,
	mPrepositions,
	mStationery,
	mBedroom,
	mJobs,
	mCountries,
	mBuildings,
	mCategories,
	mZodiac,
	mVegetables,
	mColoredShapes,
	mSchoolEvents,
	mFoods,
	mBodyParts,
	mPrices
) {
	return [
		{"title": "Fruits", "module": mFruits},
		{"title": "Vegetables", "module": mVegetables},
		{"title": "Foods", "module": mFoods},
		{"title": "Body Parts", "module": mBodyParts},
		{"title": "Colors", "module": mColors},
		{"title": "Colored Shapes", "module": mColoredShapes},
		{"title": "Categories", "module": mCategories},
		{"title": "A-Z", "module": mAZ},
		{"title": "a-z", "module": maz},
		{"title": "1-12", "module": m12},
		{"title": "1-20", "module": m20},
		{"title": "Prices", "module": mPrices},
		{"title": "Weather", "module": mWeather},
		{"title": "Days", "module": mDays},
		{"title": "Months", "module": mMonths},
		{"title": "Dates", "module": mDates},
		{"title": "Study Time", "module": mStudyTime},
		{"title": "Stationery", "module": mStationery},
		{"title": "on in under by", "module": mPrepositions},
		{"title": "My Room", "module": mBedroom},
		{"title": "Subjects", "module": mSubjects},
		{"title": "Action Verbs", "module": mActionVerbs},
		{"title": "Buildings", "module": mBuildings},
		{"title": "Jobs", "module": mJobs},
		{"title": "Countries", "module": mCountries},
		{"title": "Summer Vacation Plan", "module": mSummerVacationPlan},
		{"title": "Family", "module": mFamily},
		{"title": "Zodiac", "module": mZodiac},
		{"title": "School Events", "module": mSchoolEvents}
	];
})
